import { PHONE_NUMBER_MAIN, PHONE_NUMBER_SECONDARY, INSTAGRAM_URL, FACEBOOK_URL, VIBER_URL, TELEGRAM_URL } from "./contacts";

export { PHONE_NUMBER_MAIN, PHONE_NUMBER_SECONDARY, INSTAGRAM_URL, FACEBOOK_URL, VIBER_URL, TELEGRAM_URL };